### ISSUE TITLE
Bug PoolMenus 

### ISSUE THREAD

**Issue by foltone** [ImBaphomettt/RageUI#11]
Salut j'ai trouver un bug, quand dans la meme resource on fais 2 menu `function RageUI.PoolMenus:Example()` les menu ne fonctionnent pas.
Avez vous une solution?

Foltone#6290

**Comment by ImBaphomettt** [comment]
Good evening, this does not work because you name your poolmenu twice with the same name

```
function RageUI.PoolMenus:Example()
-- first menu
end
function RageUI.PoolMenus:One()
-- seconds menu
end
```

**Comment by foltone** [comment]
I change the name, but it does not work : 
https://streamable.com/7pvhg2
