### ISSUE TITLE
Impossible to use RageUI.CloseAll()

### ISSUE THREAD

**Issue by Xeltax** [ImBaphomettt/RageUI#13]
Hello i try  to use RageUI.CloseAll() but every time it return that the CurrentMenu is  on a nil  value i saw  that this  error arleady happened  and im sorry to reopen a issue on this but the discord  link is dead so if you can help ill appreciate.

Screen of the error :
![Screenshot_1](https://user-images.githubusercontent.com/85458421/152694993-c8370a44-94a8-4029-8486-d9c6801aa7c0.png)

My code :
`	local AmbulanceMenu = RageUI.CreateMenu("Ambulance", "Ambulance", 1, 1, "commonmenu", "gradient_nav", 5, --[[Rouge]] 0, --[[Vert]] 145, --[[Bleu]] 5);

	function RageUI.PoolMenus:Example()
		AmbulanceMenu:IsVisible(function(Items)
			local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
			-- Items
			Items:AddButton(_U('cloakroom'), "Changer vos vêtement !", { IsDisabled = false }, function(onSelected)
				if (onSelected) then
					OpenCloakroomMenu()
				end
			end)

			if Config.EnablePlayerManagement and ESX.PlayerData.job.grade_name == 'boss' then
				Items:AddButton("Action Patron", "Gestion de l'entreprise !", { IsDisabled = false }, function(onSelected)
					if (onSelected) then
						TriggerEvent('esx_society:openBossMenu', 'ambulance', function(data, menu)
							menu.close()
						end, {wash = false})
						RageUI.CloseAll()
					end
				end)
			end
	
		end, function(Panels)
		end)
	end

	RageUI.Visible(AmbulanceMenu, not RageUI.Visible(AmbulanceMenu))`

**Comment by TrAsKiN** [comment]
Hello !

You need to isolate the command in a thread.

```lua
CreateThread(function ()
    RageUI.CloseAll()
end)
```

**Comment by Xeltax** [comment]
It Works thanks !!!
