### ISSUE TITLE
Crash with RageUI.CloseAll

### ISSUE THREAD

**Issue by SkySharkx** [ImBaphomettt/RageUI#5]
Hey I currently have a problem with RageUI.
I have a menu that has RageUI.Closable disabled. So far everything is fine but as soon as I want to close with a button with RageUI.CloseAll the menu crashes. I have tried the same problem in the example.

![unknown](https://user-images.githubusercontent.com/25177502/124649745-2c540b00-de99-11eb-975b-d8d05af8ffe4.png)

**Comment by James-TREMA** [comment]
If you need support -> Riv-Tech https://discord.gg/TKX2nVq9ue
